config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get '/information', to: 'pages#information'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tickets, except: :destroy
  resources :contacts, only: [:new, :create, :edit, :update, :show]
  resources :chatrooms, only: :show do
     resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  before_create do
    opentok = OpenTok::OpenTok.new ENV["VONAGE_API_KEY"], ENV["VONAGE_API_SECRET"]
    session = opentok.create_session
    self.vonage_session_id = session.session_id
  end
  belongs_to :ticket
  has_many :messages, dependent: :destroy
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :chatroom
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :victim, class_name: 'User'
  belongs_to :worker, class_name: 'User', optional: true
  has_one :chatroom, dependent: :destroy

  enum status: [:pending, :solved]
  def self.styles
    ["I'm in danger, I need help!", "I want to use hidden live chat", "I want to speak to specialist via video chat"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :contact, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone_number, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :phone_number, :avatar])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    opentok = OpenTok::OpenTok.new ENV["VONAGE_API_KEY"], ENV["VONAGE_API_SECRET"]
    @token = opentok.generate_token @chatroom.vonage_session_id, { name: current_user.first_name }
    @ticket = @chatroom.ticket
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :contact_id, only: [:show, :edit, :update]
  def show; end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    # creating new contact with the required params
    @contact.user = current_user
    # user that contact belongs to is the user with the specified id
    if @contact.save
      redirect_to root_path
      # can be changed after the routes are determined
    else
      render :new
      # paths may change after setting the routes
    end
  end

  def edit; end

  def update
    @contact.user = current_user
    redirect_to root_path
    # can be changed after all the routes are settled
  end

  private

  def contact_id
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:full_name, :phone_number, :user_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "messages/message", locals: { message: @message }))
    else
      render "chatroom/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :information]

  def home
  end

  def information
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_contact_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_action :set_ticket, only: [:show, :update]
  def index
    @tickets = Ticket.all
  end

  def show; end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.victim = current_user
    if @ticket.save
      @chatroom = Chatroom.create(name: "Chatroom for ticket - #{@ticket.id}", ticket: @ticket)
      redirect_to chatroom_path(@chatroom)
    else
      render :new
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.update(ticket_params)
    redirect_to tickets_path
  end

  def contact_ticket
    our_user = User.find(@ticket.victim_id)
    if our_user.worker == true
      @contact_id = our_user.id
      @contact_id
    end
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:issue_type, :comment, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/show.html.erb
<div class="container-fluid mb-5">
  <div id="video_window">
    <iframe src="https://www.youtube.com/embed/videoseries?list=PLo12_MvY3Yr1h7IEquOJb1n_X3h7m0LSc" height="300" frameborder="0" allow="autoplay; encrypted-media"></iframe>
  </div>
  <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://images.unsplash.com/photo-1590452224879-867e8012a828?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)"></div>
      <ul class="details">
        <li class="author"><a href="#">Autograph Tree</a></li>
        <li class="date">Home Plant</li>
        <li class="tags">
          <ul>
            <li><a href="#">Hope</a></li>
            <li><a href="#">Power</a></li>
            <li><a href="#">Care</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Autograph Tree</h1>
      <h2>Open your doors to the Autograph Tree</h2>
      <p>Clusia is a large genus of trees and shrubs native to tropical America characterized by their branches, which grow horizontally, and their leaves, which are thick and tough. There are about 150 Clusia species, but Clusia rosea, or the autograph tree, is the only one commonly grown. It is notable for its tendency to grow on top of other plants (often strangling them). It is widely considered to be an invasive species. Another unusual quality, this species is part of the only genus of plants capable of absorbing carbon dioxide at night.</p>
    </div>
  </div>
  

  <div class="js-hiddenchat mt-5">
  <% if @ticket.issue_type == "I'm in danger, I need help!" %>
      <div>
        <p>Police is on the way!<br>
        Please stay in contact with one of our agents<br>
        </p>
      </div>
  <% elsif @ticket.issue_type == "I want to use hidden live chat" %>
    <%# <div class="js-hiddenchat"> %>
  <% else  %>
    <%# !!!!!!Video chat!!!!!! %>
    <div id="videos"
          data-controller="vonage"
          data-vonage-api-key="<%= ENV["VONAGE_API_KEY"]  %>"
          data-vonage-session-id="<%= @chatroom.vonage_session_id  %>"
          data-vonage-token="<%= @token %>"
          data-vonage-name="<%= current_user.first_name  %>">
    </div>
  <% end %>

  <h5 id="chat" class="mt-3">Chat with our team</h5>
  <div data-controller="chatbox">
    <div id="messages" data-chatroom-id="<%= @chatroom.id %>" data-target='chatbox.messages'>
      <% @chatroom.messages.each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
    </div>


    <%# WE NEED TO FIX THIS CHAT. IT SKIPS AUTHENTICATION TOKEN IN MESSAGES CONTROLLER! %>
    <div class="mb-hidebtn">
      <%= simple_form_for([ @chatroom, @message ], remote: true, html: { data: { turbolinks: "false" } }) do |f| %>
        <%= f.input :content, input_html: { data: { target: "chatbox.input" } }, label: false, placeholder: "Write your message" %>

        <%= f.submit "Send", class: "btn btn-gradient mb-3", id:"tickets_new_btn" %>

      <% end %>
    </div>
  </div>

  <%# <div>
    <%= link_to "Edit Tickets", edit_ticket_path, class: "btn btn-primary", id:"chatroom_btn" %>
    <%# <%= link_to "Home", root_path, class: "btn btn-primary", id:"chatroom_btn" %>
  <%# </div>  %>
</div>
<div class="fixed-bottom d-flex justify-content-end">
  <a class="js-hidebtn" z-index: 5 href="#"><i class="fas fa-seedling"></i></a>
</div>

app/views/contacts/edit.html.erb
<div id='new_contact_form'>
  <%= simple_form_for [@user, @contact] do |f| %>
    <%= f.input :full_name %>
    <%= f.input :phone_number %>
    <%= f.submit "Save", class: "btn btn-gradient" %>
  <% end %>
  <div style='margin-top:60px;margin-left:150px;'>
    <%= link_to "Back", contact_path(@contact), class: "btn btn-primary", id:"go_to_btn"%>
  </div>
</div>

app/views/contacts/show.html.erb
<h1 id='heading_contact'>Trusted contact  info</h1>

<div style='margin-left:70px'>
  <table class='table_whole' style='border:2px solid #D3D3D3'>
    <tbody>
      <tr>
        <th>Full Name</th>
        <th>Phone Number</th>
      </tr>
      <tr>
        <td><%= @contact.full_name %></td>
        <td><%= @contact.phone_number %></td>
      </tr>
    </tbody>
  </table>
</div>
<div style='margin-top: 40px; '>
  <button type="button" class="btn btn-link" style="margin-left:140px;" id='go_to_btn'><%= link_to 'Edit contact', edit_contact_path, id:"go_to_btn" %></button>
</div>

app/views/messages/create.js.erb
function updateDom()  {
  const input = document.querySelector('textarea');
  input.value = "";
  window.scrollTo(0,document.body.scrollHeight);
}
updateDom();

app/views/pages/home.html.erb
    <header>
      <div class="overlay">
    <h1>CareTime</h1>
    <h3>Healthy Plants</h3>
    <h5>Tips for keeping your plants healthy and happy</h5>
      <br>
    </div>
    </header>


  <div class="blog-card">
    <div class="meta">
      <div class="photo" style="background-image: url(https://images.unsplash.com/photo-1510520745063-ceaa7314a820?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)"></div>
      <ul class="details">
        <li class="author"><a href="#">Swiss Cheese Plant</a></li>
        <li class="date">Home Plant</li>
        <li class="tags">
          <ul>
            <li><a href="#">Live</a></li>
            <li><a href="#">Hope</a></li>
            <li><a href="#">Power</a></li>
            <li><a href="#">Care</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Swiss Cheese Plant</h1>
      <h2>Open your doors to the Swiss Cheese Plant</h2>
      <p> The Swiss cheese plant, Monstera adansonii, gets its name from its large, heart-shaped leaves, and as the plant ages, the leaves develop holes (called fenestration) that makes the leaves resemble Swiss cheese. Swiss cheese plant is a tropical perennial plant native to Central and South American that is typically grown as a houseplant. Swiss cheese plant is very easy to grow. It loves to climb, so provide a stake, moss stick, or trellis that it can clink to. A climbing Monstera adansonii produces larger leaves.</p>
    </div>
  </div>
  <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://images.unsplash.com/photo-1590452224879-867e8012a828?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)"></div>
      <ul class="details">
        <li class="author"><a href="#">Autograph Tree</a></li>
        <li class="date">Home Plant</li>
        <li class="tags">
          <ul>
            <li><a href="#">Hope</a></li>
            <li><a href="#">Power</a></li>
            <li><a href="#">Care</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Autograph Tree</h1>
      <h2>Open your doors to the Autograph Tree</h2>
      <p>Clusia is a large genus of trees and shrubs native to tropical America characterized by their branches, which grow horizontally, and their leaves, which are thick and tough. There are about 150 Clusia species, but Clusia rosea, or the autograph tree, is the only one commonly grown. It is notable for its tendency to grow on top of other plants (often strangling them). It is widely considered to be an invasive species. Another unusual quality, this species is part of the only genus of plants capable of absorbing carbon dioxide at night.</p>
    </div>
  </div>


   <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://images.unsplash.com/photo-1521503862198-2ae9a997bbc9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)"></div>
      <ul class="details">
        <li class="author"><a href="#">Euphorbia (Spurge) Plant</a></li>
        <li class="date">Home Plant</li>
        <li class="tags">
          <ul>
            <li><a href="#">Hope</a></li>
            <li><a href="#">Power</a></li>
            <li><a href="#">Care</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Euphorbia (Spurge) Plant</h1>
      <h2>Open your doors to the Euphorbia (Spurge) Plant</h2>
      <p>Euphorbia is a somewhat confused genus, with species and subgenera frequently added and deleted. There are annual, perennial, and biennial species within the genus, herbaceous plants and woody shrub species, and both deciduous and evergreen species. The linking characteristic is the presence of a milky white sap that in some species can be toxic. People with sensitivities to latex are most likely to react to the sap of Euphorbia plants.</p>
    </div>
  </div>

  <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://images.unsplash.com/photo-1463320898484-cdee8141c787?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)"></div>
      <ul class="details">
        <li class="author"><a href="#">Crassula Plant </a></li>
        <li class="date">Home Plant</li>
        <li class="tags">
          <ul>
            <li><a href="#">Hope</a></li>
            <li><a href="#">Power</a></li>
            <li><a href="#">Care</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Crassula Plant </h1>
      <h2>Open your doors to the Euphorbia Crassula Plant </h2>
      <p>Succulent plants have become so popular because they offer low maintenance and diverse shapes and textures, both in the garden and indoors. Crassula is a diverse and extensive genus of succulent plants, with about 350 species. Probably the most well-known is the jade plant (Crassula ovata). Many of us know it as a houseplant, but in warm climates, it grows into a shrub.</p>
    </div>
  </div>

  <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://images.unsplash.com/photo-1485902409384-e367af5b5c92?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)"></div>
      <ul class="details">
        <li class="author"><a href="#">Schefflera (Umbrella Plant)</a></li>
        <li class="date">Home Plant</li>
        <li class="tags">
          <ul>
            <li><a href="#">Hope</a></li>
            <li><a href="#">Power</a></li>
            <li><a href="#">Care</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Schefflera (Umbrella Plant)</h1>
      <h2>Open your doors to the Schefflera (Umbrella Plant)</h2>
      <p>Schefflera species are wonderful tropical plants. The larger schefflera (sometimes called the umbrella plant) features long, shiny, oval green leaves that droop gracefully from a central stalk, resembling an umbrella. A mature schefflera might have 12 to 16 leaflets from a single stalk, while an immature schefflera is more likely to have four to six. Schefflera arboricola (sometimes called dwarf schefflera) feature smaller, glossy leaves, sometimes with creamy variegation.</p>
    </div>
  </div>

   <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://images.unsplash.com/photo-1503153181849-4e4f85a341ce?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)"></div>
      <ul class="details">
        <li class="author"><a href="#">Heliotropes</a></li>
        <li class="date">Home Plant</li>
        <li class="tags">
          <ul>
            <li><a href="#">Hope</a></li>
            <li><a href="#">Power</a></li>
            <li><a href="#">Care</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Heliotropes</h1>
      <h2>Open your doors to the Heliotropes</h2>
      <p>Heliotropium, also commonly referred to as ‘heliotrope’, is a genus of flowering plants in the Boraginaceae family containing around 325 species. They are popular flowering perennials thanks to their stunning flowers and pleasant aroma and are synonymous with the ‘old cottage’ garden style. Heliotrope flowers grow in one-sided clusters that follow the sun, which led to their name which is directly derived from the Greek words helios (meaning ‘sun) and tropos (meaning ‘to turn’). Some gardeners describe the scent of the flowers as vanilla, while others insist they smell like cherry pie! Learn how to grow these attractive perennials in your garden.</p>
    </div>
  </div>


   <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://images.unsplash.com/photo-1458596376782-d1c25e7da40e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)"></div>
      <ul class="details">
        <li class="author"><a href="#">Wood Poppy</a></li>
        <li class="date">Home Plant</li>
        <li class="tags">
          <ul>
            <li><a href="#">Hope</a></li>
            <li><a href="#">Power</a></li>
            <li><a href="#">Care</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Wood Poppy</h1>
      <h2>Open your doors to the Wood Poppy</h2>
      <p>Are you looking for a colorful plant to fill the shaded space under your shrubs? Or maybe some ground cover around your trees? Yellow wood poppies are a vibrant, hardy variety of poppy.</p>
    </div>
  </div>
<div class="px-3">
<%= link_to "How can we help?", new_ticket_path, class: "btn btn-gradient my-3", id:"tickets_new_btn" %>
</div>

app/views/pages/information.html.erb
<section class="c-posts">
  <img src="https://images.squarespace-cdn.com/content/59ab0aedf14aa1fbc5860946/1540518118659-CB9Z5B49CBHJ1VMRTF7Q/2017ywca_i-believe-you_campaign-graphics-fb-banner_29482566_ver1.0_1280_720.jpg?content-type=image%2Fjpeg" width="350" height="250">

    <article class="c-posts__item">
      <h2>Domestic Violence</h2>
      <p> Domestic Violence is a pattern of Coercive tactics that can
          include physical, psychological, sexual, economic, and emotional
          abuse, perpetrated by one person against an intimate partners,
          with the goal of establishing and maintaining power and control.
          Domestic Violence occurs in all kinds of intimate relationships,
          including married couples, people who are dating, couples who
          live together, people with children in common, same-sex
          partners, people who were formerly in a relationship with the
          person abusing them, and teen dating relationships.
          Abusive behaviors are not symptoms that someone is angry or
          out of control. An abuser makes a choice to exert power and
          control over his or her partner. Abusive behaviors include
          physical, emotional, sexual, social, and financial abuse.</p>
    </article>
    <article class="c-posts__item">
      <h2>Physical Abuse</h2>
      <p>Physical abuse often begins with less violent assaults such as
          physical abuse often begins with less violent assaults such as
          pushing. As the abuse continues, however, it becomes
          increasingly violent. Abusers often target areas of the body that
          are usually covered with clothing because the injuries are less
          likely to be visible to others. Acts of physical abuse include:</p>
          <ul>
            <li>Pushing</li>
            <li>Restraining</li>
            <li>Shaking</li>
            <li>Kicking</li>
            <li>Throwing objects at the victim</li>
            <li>Target hitting</li>
            <li>Sustaied hitting</li>
            <li>Abuse planned to cause the victim to miscarry</li>
            <li>Using weapons</li>
            <li>Strangulation</li>
            <li>Homicide</li>
          </ul>
    </article>
    <article class="c-posts__item">
      <h2>Emotional Abuse</h2>
      <p>Emotional abuse is a tool used by those who want to make their
         Emotional abuse is a tool used by those who want to make their
          partners feel scared, crazy, worthless, or responsible for the
          abuse. The abuser’s goal is control over the victim. Emotional
          abuse may include:</p>
          <ul>
            <li>Making jokes about the victim</li>
            <li>Insults</li>
            <li>Criticizing the victim's competence</li>
            <li>Ignoring the victim's feelings</li>
            <li>With holding affection as a form of punishment</li>
            <li>Blaming the victim for all problems</li>
            <li>Yelling at the victim</li>
            <li>Humiliating the victim in front of others</li>
            <li>Threatening to take the children away from the victim</li>
            <li>Threatening pyhsical violance</li>
            <li>Threatening suicide to punish the victim</li>
          </ul>
    </article>
    <article class="c-posts__item">
      <h2>Sexual Abuse</h2>
      <p>Sexual abuse is one of the least discussed, but most common,
          forms of domestic violence. Sexual abuse includes:</p>
          <ul>
            <li>Sexual jokes that make the victim uncomfortable</li>
            <li>Treating women as sex objects</li>
            <li>Criticizing the victim's sexuality</li>
            <li>Using sexual jealousy as a tool of control</li>
            <li>Uncomfortable or unwanted touch</li>
            <li>Withholding sex as punishment</li>
            <li>Demanding sex</li>
            <li>Rape</li>
            <li>Sex after beatings</li>
            <li>Forcing the victim to witness or participate in sexual activity with others</li>
            <li>Sexual torture</li>
          </ul>
    </article>
     <article class="c-posts__item">
       <h2>Social Abuse</h2>
      <p>Social abuse is used to isolate the victim from others in the
        community. The fewer people the victim is connected with, the
        more control the abuser has over the victim. Examples of social
        abuse include:</p>
        <ul>
            <li>Insisting that the couple spend all time together</li>
            <li>Discouraging the victim from seeing friends or family</li>
            <li>Forbidding the victim to see friends or family</li>
            <li>Monitoring the victim’s mail or phone calls</li>
            <li>Checking the odometer</li>
            <li>Restricting access to the car or car keys</li>
            <li>Telling others the victim is crazy or abusive</li>
          </ul>
        </article>
    <article class="c-posts__item">
      <h2>Financial Abuse</h2>
      <p>busers often attempt to establish financial control over victims.
          Victims who are financially dependent on abusers have fewer
          resources for escape. Financial abuse includes: </p>
           <ul>
            <li>Making all financial decisions for the household</li>
            <li>Monitoring the victim’s spending</li>
            <li>Controlling the victim’s access to cash</li>
            <li>Controlling the victim’s access to checkbook or credit cards</li>
            <li>Refusing to let the victim work</li>
            <li>Forcing the victim to turn over income to the abuser</li>
          </ul>
    </article>
    <article class="c-posts__item">
      <h2>You Can Do Something About It!</h2>
      <p>These questions may help you determine if you or someone you know or are working with
          is being battered.
          Does someone close to you?</p>
         <ul>
            <li>Push, hit, shove, slap, kick, choke, hurt or scare you?</li>
            <li>Threaten to hurt or kill you or your family or friends?</li>
            <li>Call you names and humiliate you?</li>
            <li>Criticize the things you do and say, or the way you look?</li>
            <li>Force you to have sex against your will?</li>
            <li>Threaten to take your children?</li>
            <li>Hurt your pets or destroy things special to you?</li>
            <li>Isolate you by: taking away the car keys, money or credit cards; listening to your
                phone calls; opening your mail; locking you inside your home; or refusing to let you
                work, attend school, go to church, or form friendships?</li>
            <li> Call you or appear unexpectedly at your workplace, home, school or elsewhere to
                 check up on you?</li>
            <li>Tell you that you are crazy?</li>
            <li>If you are lesbian, bisexual or gay, threaten to “out” you or tell others of your sexual
                orientation?</li>
          </ul>
              <p>If any of these sound familiar, you may be a victim of domestic abuse.
              NOTE: Asking or answering these questions in the presence of the perpetrator or others
              may endanger you or someone else. This information must be kept confidential.</p>
    </article>
    <img src="https://images.squarespace-cdn.com/content/5ee0be2588f1e349401c832c/1592222173011-31P8RQZWGO7PBSS7VUGB/StandingTogether_Logo_ONLY-01.jpg?format=1500w&content-type=image%2Fjpeg" width="350" height="250">
</section>
  <div class="px-3">
    <%= link_to "Go back", new_ticket_path, class: "btn btn-gradient w-400 mt-3", id:"tickets_new_btn"%>
  </div>
  

app/views/tickets/index.html.erb
<h1 id='heading_contact'>Tickets</h1>

<% @tickets.each do |ticket| %>
  <div class="accordion" id="accordionExample">
    <div class="card" id='card_tickets'>
      <div class="card-header" id="headingOne">
        <h2 class="mb-0">
          <% data_t = "#collapse#{ticket.id}" %>
          <% data_c = "collapse#{ticket.id}" %>
          <button class="btn btn-link" id='accordion_buttons' type="button" data-toggle="collapse" data-target='<%= data_t %>' aria-expanded='true' aria-controls='<%= data_c %>'>
            <% if ticket.issue_type == "I'm in danger, I need help!" %>
              <p id='ticket_data'><strong>Issue Type: </strong><%= ticket.issue_type = 'Police' %></p>
            <% elsif ticket.issue_type == 'I want to use hidden live chat' %>
              <p id='ticket_data'><strong>Issue Type: </strong><%= ticket.issue_type = 'Live Chat' %></p>
            <% elsif ticket.issue_type == 'I want to speak to specialist via video chat'%>
              <p id='ticket_data'><strong>Issue Type: </strong><%= ticket.issue_type = 'Video' %></p>
            <% end %>
              <p id='ticket_data'><strong>Status: </strong><%= ticket.status %></p>
          </button>
        </h2>
      </div>
      <% div_id = "collapse#{ticket.id}"  %>
      <div id='<%=div_id%>' class='collapse hide' aria-labelledby='headingOne' data-parent='#accordionExample'>
        <div class="card-body">
          <p id='ticket_data'><strong>Comment: </strong><%= ticket.comment %></p>
          <p style='color:#1e3e2f;'><em><strong><%= link_to 'Details', ticket_path(ticket) %></em></strong></p>
        </div>
      </div>
    </div>
   </div>
<% end %>

<div>
  <%= link_to "Back to top", tickets_path, class: "btn btn-primary", id: "back_to"%>
</div>